[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
hook_source = 'call coil398#init#coc#hook_source()'
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'mfussenegger/nvim-dap'
hook_add = '''
  source ~/.config/nvim/plugins/nvim-dap.vim
'''

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
hook_add = '''
  source ~/.config/nvim/plugins/nvim-dep-ui.vim
'''

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
  source ~/.config/nvim/plugins/vim-startify.vim
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'marko-cerovac/material.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/material.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/defx.vim
'''

[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/barbar.vim
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/vim-fugitive.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
hook_add = '''
  source ~/.config/nvim/plugins/defx-icons.vim
'''

[[plugins]]
repo = "kristijanhusak/defx-git"
hook_add = '''
  source ~/.config/nvim/plugins/defx-git.vim
'''

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
  source ~/.config/nvim/plugins/previm.vim
'''

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  source ~/.config/nvim/plugins/vim-closetag.vim
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
  source ~/.config/nvim/plugins/rainbow.vim
'''
